
spring.data.monodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=juornaldb


# IF NEED TO AUTHENTICATE
#spring.data.mongo.username=myjournaluser
#spring.data.mongo.password=mypassword